---
title: '<div class="jumbotron"><h1 class="title toc-ignore display-3" align="center">Data Visualisation in R</h1><p class="lead" align="center">Danielle Navarro</p></div>'
output:
  html_document:
    theme: flatly
    highlight: textmate
    css: mystyle.css
pagetitle: "Data Visualisation"
---

```{r,echo=FALSE}
rm(list=objects()) # start with a clean workspace
```

Participants will need a recent installation of R and RStudio. Package dependencies are listed below, all of which should be available on CRAN.

- `tidyverse`
- `here`
- `hexbin`
- `gganimate`
- `sf`
- `usethis`
- `scico`

A link to the course material will appear shortly! The content will be organised around a series of hands on exercises, each associated with a brief discussion of core concepts in ggplot2 and gganimate. The key topics are:

- Introduction to ggplot2
- Understanding aesthetics
- Understanding geoms
- Structure of a plot layer
- Controlling geom positions
- Facetting plots
- Statistical transformations
- Customising position scales
- Customising colour/fill scales
- Co-ordinate transformations
- Customising the theme
- Writing ggplot2 extensions (in brief)
- Introduction to gganimate 
- Exploring gganimate functionality
- Understanding how tweening works (*maybe)



